"""Regenerate the queue file from card frontmatter.

The queue is a cached view, always rebuilt from scratch, so it can never drift from
the cards themselves. Day-counts appear in exactly one place — the cooling dashboard —
because a backlog count is discouraging and an inconsistency signal is useful.
"""

import datetime

from . import card

DEFAULT_TIERS = ("P0", "P1", "P2")
UPCOMING_DAYS = 7

HEADER = """\
# Review Queue

Generated by `spacedeck requeue` from card frontmatter under the configured cards
directory. **Do not hand-edit** — the cards are the source of truth and this file is
rewritten wholesale on every session.
"""


def load(cards_dir):
    """Every card under `cards_dir`, in path order.

    Non-card Markdown (a README, an index, a queue file written into the same tree)
    is skipped. A file that opens like a card but fails to parse raises, because a
    silently dropped card is a card that stops being reviewed.
    """
    return [card.read(p) for p in sorted(cards_dir.rglob("*.md")) if card.looks_like_card(p)]


def _tier_rank(c, tiers):
    try:
        return tiers.index(c.fields.get("tier", ""))
    except ValueError:
        return len(tiers)


def _sort_key(c, tiers):
    return (card.due_date(c), _tier_rank(c, tiers))


def _active(cards):
    return [c for c in cards if c.fields.get("status") == "active" and card.due_date(c)]


def due(cards, today, tiers=DEFAULT_TIERS):
    tiers = list(tiers)
    ready = [c for c in _active(cards) if card.due_date(c) <= today]
    return sorted(ready, key=lambda c: _sort_key(c, tiers))


def upcoming(cards, today, tiers=DEFAULT_TIERS):
    tiers = list(tiers)
    horizon = today + datetime.timedelta(days=UPCOMING_DAYS)
    soon = [c for c in _active(cards) if today < card.due_date(c) <= horizon]
    return sorted(soon, key=lambda c: _sort_key(c, tiers))


def _line(c):
    return (
        f"- [ ] {c.fields['subject']} · {c.fields['topic']} — "
        f"rung: {c.fields['rung']} — due {c.fields['next_due']}"
    )


def _last_seen(c):
    dates = [datetime.date.fromisoformat(h["date"]) for h in c.history]
    return max(dates) if dates else None


def _cooling(cards, today):
    freshest = {}
    for c in cards:
        if c.fields.get("status") != "active":
            continue
        seen = _last_seen(c)
        if seen is None:
            continue
        subject = c.fields["subject"]
        freshest[subject] = max(freshest.get(subject, seen), seen)

    rows = []
    for subject, seen in sorted(freshest.items()):
        days = (today - seen).days
        icon = "🔥" if days <= 3 else ("🥶" if days <= 10 else "🧊")
        rows.append((days, f"- {subject} {icon} {days}d"))
    return [row for _, row in sorted(rows, key=lambda r: r[0])]


def render(cards, today, tiers=DEFAULT_TIERS):
    active = [c for c in cards if c.fields.get("status") == "active"]
    retired = [c for c in cards if c.fields.get("status") == "retired"]

    out = [HEADER, ""]
    out.append(
        f"_Last updated: {today.isoformat()}_ · "
        f"Active cards: {len(active)} · Retired: {len(retired)}"
    )
    out += ["", "## Due today", ""]
    out += [_line(c) for c in due(cards, today, tiers)] or ["_(nothing due)_"]
    out += ["", "## Upcoming (next 7 days)", ""]
    out += [_line(c) for c in upcoming(cards, today, tiers)] or ["_(none)_"]
    out += ["", "## Retired", "", f"{len(retired)} card(s)."]
    out += ["", "## Cooling dashboard", ""]
    out += ["Days since each subject was last touched. 🔥 ≤3d · 🥶 4–10d · 🧊 ≥11d.", ""]
    out += _cooling(cards, today) or ["_(no active cards)_"]
    return "\n".join(out) + "\n"


def rebuild(cards_dir, queue_file, today, tiers=DEFAULT_TIERS):
    queue_file.write_text(render(load(cards_dir), today, tiers), encoding="utf-8")
